version: "3.1"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://postgres:9781331@db/noteapp

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 9781331
      POSTGRES_USER: postgres
      POSTGRES_DB: noteapp
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
